### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [jakjare/projekt_js_automat_MPK#1]
Załączam uwagi. Spora większość dotyczy detali, ale punkty 11. i 17. mogą doprowadzić do większych zmian w projekcie.

1. [`from logika import *`](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/gui.py#L1) powoduje powstanie w bieżącym module nieokreślonej liczby nieokreślonych nazw, które dezorientują czytelnika (2. rozdział Poradnika).
2. Albo [żmudna lista zakupów do zrobienia w module](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/gui.py#L2), albo następny wiersz. Wg Google lepszy następny wiersz (2. rozdział).
3. Powtarzające się stałe, np. `"#00a2ff"`, `"white"` nazwać zgodnie z przeznaczeniem (nie z kolorem, bo wtedy gdyby Pan zechciał zmienić kolor, zostałoby `WHITE = "yellow"`; 2. rozdział).
4. `"Arial 15"` itp. — też.
5. W wierszach [tego rodzaju](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/gui.py#L14) można zastosować trik dla uniknięcia obciachu (koniec 2. rozdziału): przenieść tylko końcowy `)` o 1 niżej. Albo podzielić je gdzieś w środku. Co kto lubi.
6. Literówki [tu](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/gui.py#L40), [tu](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/gui.py#L168) i [tu](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/logika/bilety.py#L10).
7. [Zbędne `()`](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/logika/bilety.py#L1). [Tu](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/logika/system.py#L21) też.
8. Do [`cena`](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/logika/bilety.py#L11) warto dodać `_zł` i `_gr` (uogólnienie 1. punktu 3. rozdziału).
9. [Tutaj](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/logika/bilety.py#L29) warto napisać `cena=0`.
10. [Tutaj](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/logika/bilety.py#L35) można np. `skasowany = ["Nie", "Tak"][self.__skasowany]` i użyć jednego formatu; wiersz podzielić.
11. [Tutaj](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/logika/pieniadze.py#L27) i niżej lepiej z listy nominałów zrobić nazwaną stałą na górze modułu i użyć `{x: [] for x in NOMINAŁY_GR}`. ALE: nie rozumiem jednego: po co te listy i cała klasa `Pieniądz`? Czyż każda moneta i banknot o tym samym nominale nie są jednakowe? Co by było, gdyby zamiast list trzymać liczniki nominałów: `{1: 5, 2: 3, 5:0, ...}`? Mogą być w słowniku inicjalizowane na 0 albo w `collections.Counter`.
12. [Proszę przeczytać punkt o pętlach z 3. rozdziału](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/logika/pieniadze.py#L74) (tu pasuje `zip()`).
13. [Tu](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/logika/system.py#L44) wprawdzie uszło Panu na sucho przekazanie `[]` jako domyślnej wartości, ale zawsze lepiej `None`. [Losowy blog z wyjaśnieniem](https://florimond.dev/blog/articles/2018/08/python-mutable-defaults-are-the-source-of-all-evil/). Nadto za dużo spacji. Czy używa Pan pylinta (2. rozdział)?
14. [To](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/logika/system.py#L49) się Panu wtedy uprości. Mimo to proszę przeczytać punkt o instrukcjach warunkowych z 2. rozdziału.
15. [Tutaj](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/logika/system.py#L55) lepiej użyć `with open('kasa.dat', 'w') as plik:`.
16. [Zbędne `str()`](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/logika/system.py#L58). Nadto polecam zapoznanie się z f-stringami. W tym miejscu bardzo pasują; w innych lepiej nie zastępować nimi `.format()`.
17. [Tu](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/logika/system.py#L68) mam podobne pytanie jak w punkcie 11. Zamiast listy można by chyba użyć `collections.Counter` z `+= 1` i `-= 1` dla danych kluczy.
18. [`id` to zła nazwa zmiennej](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/logika/system.py#L83). Pylint!
19. [Tutaj](https://github.com/jakjare/projekt_js_automat_MPK/blob/00b7033883a85547eb8a40b86282ef4bf292ae9a/logika/system.py#L119) użyć ww. stałej (pewnie będzie na nią potrzebny mały modułek, żeby nie kopiować). Nadto ten fragment dobrze by było wydzielić do osobnej funkcji przyjmującej `kasa` i `do_zaplaty`, a zwracającej `reszta` i `do_zaplaty`, po czym przetestować. Używanie wszędzie `-p_wart` jest mylące. Lepiej je nazwać po prostu `i` i puścić jako liczbę dodatnią od wysokich wartości ku niskim (i używać `[i]`).
20. Popieram Pana plan co do testów. Testowanie GUI byłoby od rzeczy. Z tym, że testy np. do modułu `pieniadze` mają być w `pieniadze_test.py` itd., a w środku osobne klasy `TestPieniadz` i `TestPrzechowywacz` (3. rozdział).

**Comment by MarcinCiura** [comment]
11. i 17. `collections.Counter` ma metody, których Pan nie potrzebuje; `collections.defaultdict(int)` jest lepiej skrojony pod to zadanie.

**Comment by jakjare** [comment]
- Poprawiłem kod według uwag 1-10, 12-16, 18-19. Nie jestem pewien o co dokładnie chodzi z tą stałą i modułem w 19 punkcie. Chodzi o to, żeby była jeszcze jedna metoda, która ma sprawdzać czy automat może wydać resztę?
- W 11. punkcie zmieniłem według Pańskiego zalecenia ale nie chciałem pozbyć się klasy `Pieniadz()`. Uważam, że może ona rozszerzyć możliwości automatu np. rozróżniając walutę. Czy może to zostać tak jak teraz?
- W 17. użyłem `collections.defaultdict(int)`, faktycznie musiałem zmienić trochę rzeczy w projekcie ale rozszerzyło to możliwości GUI. Teraz koszyk wyświetla dodatkowo ilość dodanych do koszyka biletów danego typu, przez co można dokonać zakupu dowolnej ilości każdego typu w jednej transakcji. Teraz automat nie kopiuje tych samych biletów x razy do koszyka tylko dodaje bądź usuwa ich ilość.
- Mam jeszcze jeden problem jeśli chodzi o sprzątanie. Jak powinienem to zrobić?

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany. Jak nie ma po czym sprzątać, to nie trzeba. W punkcie 19. chodzi o:
* Użycie stałej z listą nominałów, która gdzieś już powinna być gotowa. A żeby nie importować siostrzanego modułu, lepiej tę stałą (i może jeszcze jakieś inne) trzymać w jeszcze innym, osobnym module, importowanym przez oba moduły, które jej potrzebują.
* Wyjęcie najbardziej skomplikowanej części tej metody do funkcji po to, żeby łatwo ją było testować bez konieczności robienia obiektów, w których połowa atrybutów nie ma znaczenia dla tego testowania.

Reszta może być.

**Comment by jakjare** [comment]
Według zalecenia wyciągnąłem z metody `dodaj_pieniądz()` element zwracania reszty do funkcji. Używanie `-i` jest tutaj konieczne, ponieważ wtedy funkcja sprawdza czy może wydać resztę od największego nominału do najmniejszego, przez co jest większe prawdopodobieństwo, że automat będzie mógł wydawać resztę dłużej, ponieważ nie pozbędzie się mniejszych nominałów od razu. Wyciągnąłem też listę nominałów do stałej i umieściłem w module `stale.py`. Dzięki temu użyłem w niektórych miejscach Dictionary Comprehension. Czy wyciągnąć też stałe z `gui.py` do tego modułu? Zabieram się za pisanie testów.

**Comment by jakjare** [comment]
Utworzyłem moduły do testowania pakietu logika. Czy tak to ma wyglądać? Coś zmienić? Poprawić?
Mam taki problem z importowaniem w pakiecie `logika`, mianowicie jak robiłem te moduły testowe to Python zgłaszał błąd, że nie zna takiego pakietu `logika`. Musiałem komentować fragment `from logika import ...` i zastępować go samym importem. Jak rozwiązać ten problem?

**Comment by MarcinCiura** [comment]
1. Używanie `-i` nie jest konieczne. Wystarczy, żeby `i` jechało z góry na dół, tak jak napisałem.
2. Jeśli stałe w `gui.py` są nieużywane poza nim, to ich nie wyciągać.
3. Przypuszczam, że w `bilety_test.py` zadziała `from logika import bilety`, tylko trzeba pamiętać, żeby katalogiem bieżący przy uruchamianiu testów nie był katalog `logika`, tylko ten, w którym siedzi `gui.py`. Jakby dalej nie działało, proszę pisać.
4. Testy są bardzo dobre, tylko [to](https://github.com/jakjare/projekt_js_automat_MPK/blob/085c86605d7d067acbadac22ac901593bf258c73/logika/system_test.py#L11) itp. powyciągać do `def setUp(self):`.
4. [Importy nie w funkcjach, tylko na górze tego pliku](https://github.com/jakjare/projekt_js_automat_MPK/blob/085c86605d7d067acbadac22ac901593bf258c73/__main__.py#L2).

**Comment by jakjare** [comment]
1.  Faktycznie, nie popatrzyłem na to w taki sposób wcześniej. Zmieniłem według zalecenia, działa.
2.  Dobrze.
3.  Zrobiłem według zalecenia. Działa tylko przez: `python -m unittest discover logika "*_test.py"` z katalogu głównego projektu
4.  Zmieniłem według zalecenia. Wszystkich testów jest aktualnie 14. Wszystkie pomyślne.
5.  Poprawiłem.

W takim razie to chyba wszystko co mogłem poprawić na ten moment. Czy ma Pan Doktor jeszcze jakieś uwagi do projektu? Coś zmienić? Poprawić? Jeśli nie to w jaki sposób mogę oddać projekt do oceny?

**Comment by MarcinCiura** [comment]
1. [Czemu nie `from collections`](https://github.com/jakjare/projekt_js_automat_MPK/blob/5a17415321504a520600249634f3fcdcce96d389/gui.py#L3)?
2. Nazwa pliku `__main__.py` jest zła. Zmienić na cokolwiek bez podkreśleń. Stała `'__main__'`, z którą jest porównywane `__name__`, jest magicznie przydzielana plikowi, który został uruchomiony.
3. [Posortować importy jak należy](https://github.com/jakjare/projekt_js_automat_MPK/blob/5a17415321504a520600249634f3fcdcce96d389/__main__.py#L1) (2. rozdział); rozbić na `from logika import bilety` itd.
4. Po co [ta pętla](https://github.com/jakjare/projekt_js_automat_MPK/blob/5a17415321504a520600249634f3fcdcce96d389/__main__.py#L21)? Użyć stałej `NOMINAŁY_GR`.
5. [`NOMINAŁY` i `wartosc`](https://github.com/jakjare/projekt_js_automat_MPK/blob/5a17415321504a520600249634f3fcdcce96d389/logika/pieniadze.py#L9) zmienić zgodnie z 1. punktem 3. rozdziału. Podobnie `.suma()` itp. Przy tworzeniu Pieniędzy nie pisać `Pieniadz(5)`, tylko `Pieniadz(wartość_zł=5)`.
6. [`p` to zła nazwa](https://github.com/jakjare/projekt_js_automat_MPK/blob/5a17415321504a520600249634f3fcdcce96d389/logika/pieniadze.py#L44). Dlaczego Pan nie słucha pylinta?

**Comment by jakjare** [comment]
6. Niestety pylint mi nie działa. Ponad 3 godziny starałem się to zainstalować/naprawiać, i nic. Wyświetla się taki błąd: 
````
18:12	Unexpected Exception Caught
			The scan failed due to an exception: com/jetbrains/python/PythonFileType
			java.lang.NoClassDefFoundError: com/jetbrains/python/PythonFileType

			at com.leinardi.pycharm.pylint.util.FileTypes.isPython(FileTypes.java:32)

			at com.leinardi.pycharm.pylint.checker.PsiFileValidator.isValidFileType(PsiFileValidator.java:46)

			at com.leinardi.pycharm.pylint.checker.PsiFileValidator.isScannable(PsiFileValidator.java:38)

			at com.leinardi.pycharm.pylint.checker.ScannableFile.lambda$createAndValidate$0(ScannableFile.java:93)

			at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)

			at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)

			at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)

			at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)

			at java.base/java.u... (show balloon)

18:12	Unexpected Exception Caught
			The scan failed due to an exception: com/jetbrains/python/PythonFileType
			java.lang.NoClassDefFoundError: com/jetbrains/python/PythonFileType

			at com.leinardi.pycharm.pylint.util.FileTypes.isPython(FileTypes.java:32)

			at com.leinardi.pycharm.pylint.checker.PsiFileValidator.isValidFileType(PsiFileValidator.java:46)

			at com.leinardi.pycharm.pylint.checker.PsiFileValidator.isScannable(PsiFileValidator.java:38)

			at com.leinardi.pycharm.pylint.checker.ScannableFile.lambda$createAndValidate$0(ScannableFile.java:93)

			at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)

			at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)

			at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)

			at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)

			at java.base/java.u... (show balloon)

18:12	Unexpected Exception Caught
			The scan failed due to an exception: com/jetbrains/python/PythonFileType
			java.lang.NoClassDefFoundError: com/jetbrains/python/PythonFileType

			at com.leinardi.pycharm.pylint.util.FileTypes.isPython(FileTypes.java:32)

			at com.leinardi.pycharm.pylint.checker.PsiFileValidator.isValidFileType(PsiFileValidator.java:46)

			at com.leinardi.pycharm.pylint.checker.PsiFileValidator.isScannable(PsiFileValidator.java:38)

			at com.leinardi.pycharm.pylint.checker.ScannableFile.lambda$createAndValidate$0(ScannableFile.java:93)

			at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)

			at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)

			at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)

			at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)

			at java.base/java.u... (show balloon)`
```

Nie potrafię sobie z tym poradzić. Szukałem też pomocy w internecie ale też nic.

**Comment by MarcinCiura** [comment]
Nie puszczać pylinta z pycharma, tylko z wiersza poleceń.

**Comment by jakjare** [comment]
1.  Poprawiłem.
2.  Zmieniłem na automat.py. Może tak zostać? Nie byłem pewien czy plik główny powinien się jakoś specjalnie nazywać.
3.  Starałem się zrobić według podpowiedzi pylint.
4.  Usunąłem pętlę i zrobiłem wszystko ze stałej.
5.  W `NOMINAŁY i wartosc` zmieniłem nazwę zmiennej ale nie wiem czy o to chodziło. Przy tworzeniu pieniędzy zmieniłem.
6.  Jak puszczałem pylinta z wiersza poleceń to działało. Dziękuję za pomoc.

**Comment by MarcinCiura** [comment]
1. Te `del` w `main()` raczej niepotrzebne.
2. Dobra zmiana w 5. Przydałoby się jeszcze `self.__wartosc` na `self.__wartosc_gr`, `def wartosc(self):` na `def wartosc_gr(self):` i podobnie z ceną w `Bilet`, bo teraz naprawdę trudno się połapać, w czym są wyrażone te wartości i ceny. Nie widzę zmiany nazwy `NOMINAŁY`.

**Comment by jakjare** [comment]
1.  Poprawiłem.
2.  Zmieniłem nazwy tych zmiennych i metod. Teraz faktycznie łatwiej się połapać w kodzie. Zmieniłem również NOMINAŁY na NOMINAŁY_GR.

Czy mogę coś jeszcze poprawić?

**Comment by MarcinCiura** [comment]
`suma()` na `suma_zł()` i na tym koniec.

**Comment by jakjare** [comment]
Zrobione. Bardzo dziękuję Panu Doktorowi za nieocenioną pomoc. Ostatnie dwa pytania: Aby oddać projekt do oceny to wystarczy tylko wysłać na elfie? Trzeba robić jeszcze ten raport projektu czy nie? Bo już w zasadzie nie wiadomo do których wytycznych się stosować i kto ostatecznie będzie oceniał projekt.

**Comment by MarcinCiura** [comment]
Gratuluję pracowitości. Jest Pan trzeci.
Ja też nie wiem, czy będę oceniał projekty sam, czy z drem Gąciarzem. Co do raportu, proszę postąpić zgodnie z wytycznymi podanymi dla całego roku przez dra Gąciarza.

**Comment by jakjare** [comment]
Projekt przesłany na elfie razem z raportem. Jeszcze raz bardzo dziękuję za pomoc.
